feat(admins/stats): add admin stats
marzneshin/marzneshin pull request #730
Opened 2024-12-10 20:55 UTC by erfjab

## Description

Provide a small description of Pull Request.

## UI Changes

-
-

### Screenshots

## API Changes

## Checklist
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests (stories, interaction tests, unit tests, e2e tests) to cover my changes.
- [ ] I have added tests to cover my changes.

## Related Issues

Closes

- #
- #

2024-12-10 21:00 UTC, erfjab commented
اگر @khodedawsh موافق باشی یه فیلد removed at اضافه کنیم تا بتونیم آمار حذفی هارو هم به لیست اضافه کنیم.

2024-12-13 03:09 UTC, erfjab commented
ایرادی که خودم میتونگ ازش بگیرم اینه که تعداد کوئری های زده شده زیاده. باید بهینه تر بشه.

2024-12-14 07:11 UTC, khodedawsh commented
> اگر @khodedawsh موافق باشی یه فیلد removed at اضافه کنیم تا بتونیم آمار حذفی هارو هم به لیست اضافه کنیم. 

نیاز نیست از قبل هست

2024-12-14 07:12 UTC, khodedawsh requested changes
به ازای هر ادمین n تا کوئریه. همچنین باید تو دامین ادمین باشه.

2024-12-14 09:14 UTC, erfjab commented
> به ازای هر ادمین n تا کوئریه. همچنین باید تو دامین ادمین باشه.

خب اینو خودمم گفتم. حجم کوئری ها زباده. باید فیکسش کنم.
تو دامین ادمین نیست چون آمار همشون رو یجا میگیریم.
چون میخواییم یه جدول به داشبورد اضافه بشه که یجا نشون بده همشو.

2025-02-16 14:27 UTC, closed without merging